trigger:
  branches:
    include:
      - main
      - qa
      - dev

variables:
  - name: imageRepository
    value: myAppDevOps
  - name: containerRegistry
    value: myregistry.azurecr.io
  - name: aksResourceGroup
    value: my-aks-rg
  - name: aksClusterName
    value: my-aks-cluster
  - name: dockerfilePath
    value: Dockerfile
  - name: k8sManifests
    value: k8s/deployment.yml

stages:
  - stage: Build
    displayName: Build and Push Docker Image
    jobs:
      - template: templates/build.yml

  - stage: Test
    displayName: Run Unit Tests
    dependsOn: Build
    jobs:
      - template: templates/test.yml

  - stage: Deploy
    displayName: Deploy to AKS
    dependsOn: Test
    jobs:
      - template: templates/deploy.yml
